name: Manual Docker Image CI

on:
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
       ls -ld docker/Dockerfile
       wget https://raw.githubusercontent.com/truatpasteurdotfr/rivanna-docker/master/alphafold/2.1.1/Dockerfile -O docker/Dockerfile
       ls -ld docker/Dockerfile
       docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)
